---
title: "The Most Expensive and Deadliest Weather Events in the United States, 1950-2011"
author: "apyle@github.com"
date: "2015-09-16"
output: 
  html_document:
    keep_md: true
---

<br />
<hr />

## Synopsis

Answer these two questions:

1. Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?
1. Across the United States, which types of events have the greatest economic consequences?

<br />
<hr />

## Data

<br />
<hr />

## Data Processing

```{r setoptions, echo = TRUE}
# keep the chatter down so the write-up stays clean
options(warn = -1)

# make sure we have access to the knitr library for setup and housekeeping
# suppressWarnings should not be necessary since we have used the warn option
# but using it to reinforce the idea that we want to keep the write-up clean.
suppressWarnings(library(knitr))

# set knitr default option values, specifically echo, turning on the cache and
# setting its location, and specifying the figure directory
opts_chunk$set(echo = TRUE, 
               cache = TRUE, 
               cache.path = "cache/", 
               fig.path = "figure/")
```

<br />
<hr />

```{r}

# We only need the injury and fatality counts to answer the first question and the property and crop damage for the second question. This will allow us to not load the values we don't need, saving memory and processing time
col_classes <- c("NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "character", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "numeric", "numeric", "numeric", "character", "numeric", "character", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL")
my.file <- bzfile("repdata_data_StormData.csv.bz2")
my.data <- (read.csv(my.file, colClasses = col_classes))
my.factor <- as.factor(my.data$EVTYPE)
summary(my.factor)

```

## Results

<br />
<hr />

## Conclusion

